#!/bin/bash

echo xmranon - NERVA MacOS Installer


# Check that Homebrew is installed and install if not
if test ! $(which brew)
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /tmp/homebrew-install.log
fi

# Update any existing homebrew recipes
/usr/local/bin/brew  update

# Upgrade any already installed shizz
/usr/local/bin/brew upgrade --all


# Install desired packages
/usr/local/bin/brew install openSSL
echo "OpenSSL successfully installed"
/usr/local/bin/brew install boost
echo "Boost successfully installed"
/usr/local/bin/brew install miniupnpc
echo "miniupnpc successfully installed"
/usr/local/bin/brew  tap jmuncaster/homebrew-header-only
/usr/local/bin/brew install cmake
export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2p/
export OPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2p/include/
/usr/local/bin/cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2p/
/usr/local/bin/cmake -DOPENSSL_LIBRARIES=usr/local/Cellar/openssl/lib
/usr/local/bin/cmake -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2p/include/
echo "CMake successfully installed"
echo " OpenSSL successfully copied to Brew directory "
git clone --recursive https://bitbucket.org/nerva-project/nerva
echo "Nerva project has successfully cloned"
cd nerva
mkdir build && cd build
/usr/local/bin/cmake ..
make
echo "Make completed"
mkdir ~/Desktop/NervaWallet
echo "Directory Created"
cp ~/Desktop/NervaInstaller.app/Contents/Resources/nerva/build/bin/* ~/Desktop/NervaWallet/
echo "Wallet has been created on your desktop"

# Remove brew shizz
/usr/local/bin/brew  cleanup

~/Desktop/NervaWallet/nervad
~/Desktop/NervaWallet/nerva
